version: "3"

services:
  collector:
      image: otel/opentelemetry-collector-contrib:latest
      command: ["--config=/etc/otel-collector-config.yaml"]
      volumes:
        - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      networks:
        - the-teplate-network
      ports:
        - "4317:4317"     # OTLP over gRPC receiver
        - "4318:4318"     # OTLP over HTTP receiver
      depends_on:
        - jaeger

  jaeger:
    image: jaegertracing/jaeger:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp" # UDP port for receiving traces
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # Jaeger collector HTTP port
      - "14250:14250"   # gRPC for Jaeger
    networks:
      - the-teplate-network

networks: 
  the-teplate-network:
    external: true