version: '3.4'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    volumes:
        - ./seq:/data
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - the-teplate-network

networks: 
  the-teplate-network:
    external: true